version: "3"

services:
  db:
    build:
      context: ./dockerPostgres
      dockerfile: db.Dockerfile
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: kruger
      POSTGRES_DB: krugger_vacuna
      POSTGRES_PASSWORD: Patito.123@
    ports:
      - "5432:5432"
  springboot-docker-container:
    image: springboot-krugger_vacunas
    container_name: springboot-krugger_vacunas
    ports:
      - "8090:8090"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db