version: "3"

services:
  basedatos:
    build:
      context: ./dockerPostgres
      dockerfile: db.Dockerfile
    container_name: basedatos
    hostname: basedatos
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: vacunas
      POSTGRES_PASSWORD: Patito.123@
    ports:
      - "5432:5432"
  springboot-docker-container:
    image: back-vacuna
    container_name: back-vacuna
    ports:
      - "8090:8090"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - basedatos